language:
  - node_js
  - ruby
rvm: "2.2"
node_js: "6"
os:
  - linux
  - osx
script: ./script/travis-build.sh
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - libgnome-keyring-dev
      - icnsutils
      - graphicsmagick
      - ruby
cache:
  directories:
    - node_modules
    - app/node_modules
    - ~/.electron
install:
  - npm install
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then gem install fpm; fi
  - npm prune
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl https://repository.certum.pl/cscasha2.pem >> /tmp/bundle.crt; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then security import "/tmp/bundle.crt" -k ~/Library/Keychains/login.keychain -T /usr/bin/codesign; fi
notifications:
  email:
    on_success: never
    on_failure: change