platform:
  - x86
os: unstable
install:
  - ps: Install-Product node 6
  - git reset --hard HEAD
  - npm install npm -g
  - npm install
  - npm prune
skip_tags: true
test_script:
  - npm run test
  - npm run standard
deploy_script: npm run dist
deploy: off
cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - 'app\node_modules'
  - '%userprofile%\.electron'
environment:
  GH_TOKEN:
    secure: oXAtU/2izFnd/DW9h0Lt0iC2cvp+SLSjwZukkwsihL/bIktOV54XfxvDu05kbtIm